Repository verybadcat/CSharpMath, pull requests merged in 2019-11, with the labels that each got.

#70 Show caret by itself
  CSharpMath.Rendering/MathKeyboard.cs
Labels: Resolution/Implemented, Type/Enhancement

#73 Fix HandleScriptButton
  CSharpMath.Editor.Tests/MathKeyboardTests.cs
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
Labels: Resolution/Fixed, Type/Bug

#75 Delete and gitignore Android Resource.designer.cs
  .gitignore
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.Android/Resources/Resource.designer.cs
Labels: Resolution/Implemented, Type/Housekeeping

#76 Don't put a placeholder into a new run
  CSharpMath/Display/Text/AttributedStrings/AttributedGlyphRun.cs
Labels: Resolution/Fixed, Type/Bug

#74 Do not show caret when placeholder is in an active state
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
Labels: Resolution/Implemented, Type/Enhancement

#68 Remove from nucleus properly
  CSharpMath.Editor.Tests/MathKeyboardTests.cs
  CSharpMath.Editor/Extensions/MathListEditingExtensions.cs
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
Labels: Resolution/Implemented, Type/Enhancement

#80 Removed unnecessary dependancy from CSharpMath.Analyzers
  CSharpMath/CSharpMath.csproj
Labels: Resolution/Implemented, Type/Housekeeping

#88 Scoping in case statements
  CSharpMath/Typesetting/Typesetter.cs
Labels: Type/Housekeeping

#90 Add mathkeyboard test using random inputs
  CSharpMath.sln
  TestsInFSharp/Program.fs
  TestsInFSharp/TestsInFSharp.fsproj
  TestsInFSharp/UnitTest1.fs
Labels: Resolution/Implemented, Type/Housekeeping

#92 -Fixed mathlist to latex subscript and superscript order
  CSharpMath.Tests/PreTypesetting/MathListBuilderTest.cs
  CSharpMath/Atoms/Factories/MathListBuilder.cs
Labels: Type/Housekeeping

#97 Using of xunit for TestsInFSharp project
  TestsInFSharp/TestsInFSharp.fsproj
  TestsInFSharp/UnitTest1.fs
Labels: Resolution/Implemented, Type/Housekeeping

#96 Adjust tests
  CSharpMath.Editor.Tests/MathKeyboardTests.cs
Labels: Resolution/Implemented, Type/Housekeeping

#98 Fix navigation when subIndex is BetweenBaseAndScripts
  CSharpMath.Editor.Tests/MathKeyboardTests.cs
  CSharpMath.Editor/Extensions/MathListEditingExtensions.cs
Labels: Aspect/Editor, Resolution/Fixed, Type/Bug

#93 BiDictionary improvements
  CSharpMath.Tests/Generic/BiDictionaryTests.cs
  CSharpMath/Generic/BiDictionary.cs
Labels: Resolution/Implemented, Type/Enhancement

#100 Add an additional check to prevent NRE
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
Labels: Resolution/Fixed, Type/Bug

#101 Disallow navigation to a BetweenBaseAndScripts position when base is placeholder
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
Labels: Resolution/Implemented, Type/Enhancement

#102 Adjusting of insertion for BothRoundBrackets and Absolute from BetweenBaseAndScripts position
  CSharpMath.Editor.Tests/MathKeyboardTests.cs
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
Labels: Resolution/Fixed, Type/Bug
