Repository verybadcat/CSharpMath, pull requests merged in 2019-10, with the labels that each got.

#62 Put null-case back to the top
  CSharpMath/Atoms/Factories/MathAtoms.cs
Labels: Resolution/Fixed, Type/Bug

#63 Include FusedAtoms in copy constructor
  CSharpMath.Tests/PreTypesetting/MathListTest.cs
  CSharpMath/Atoms/Atom/MathAtom.cs
Labels: Editor, Resolution/Fixed, Type/Bug

#65 Skip scripted displays when calculate Range.End
  CSharpMath.Editor.Tests/IndexForPointTests.cs
  CSharpMath.Editor.Tests/PointForIndexTests.cs
  CSharpMath.Editor/Extensions/DisplayEditingExtensions.Fraction.cs
  CSharpMath.Editor/Extensions/DisplayEditingExtensions.List.cs
  CSharpMath.Editor/Extensions/DisplayEditingExtensions.Radical.cs
  CSharpMath/Display/MathListDisplay.cs
Labels: Resolution/Fixed, Type/Bug

#66 Ported into net standard 2.0
  CSharpMath.Analyzers/CSharpMath.Analyzers/CSharpMath.Analyzers.csproj
  CSharpMath.Editor/CSharpMath.Editor.csproj
  CSharpMath.Editor/Keyboards/MathKeyboard.cs
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.Android/CSharpMath.Forms.Example.Android.csproj
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.Android/Resources/Resource.designer.cs
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.UWP/CSharpMath.Forms.Example.UWP.csproj
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.WPF/App.config
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.WPF/CSharpMath.Forms.Example.WPF.csproj
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.WPF/Properties/Settings.Designer.cs
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.WPF/packages.config
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.iOS/CSharpMath.Forms.Example.iOS.csproj
  CSharpMath.Forms.Example/CSharpMath.Forms.Example/CSharpMath.Forms.Example.csproj
  CSharpMath.NuGetPackageTests.CSharp/CSharpMath.NuGetPackageTests.CSharp.UWP/CSharpMath.NuGetPackageTests.CSharp.UWP.csproj
  CSharpMath.NuGetPackageTests.CSharp/CSharpMath.NuGetPackageTests.CSharp/CSharpMath.NuGetPackageTests.CSharp.csproj
  CSharpMath.Rendering/CSharpMath.Rendering.csproj
  CSharpMath.Rendering/Drawing/GraphicsContext.cs
  CSharpMath.Rendering/Painter.cs
  CSharpMath.SkiaSharp/CSharpMath.SkiaSharp.csproj
  CSharpMath.SkiaSharp/MathPainter.cs
  CSharpMath.SkiaSharp/TextPainter.cs
  CSharpMath/CSharpMath.csproj
  CSharpMath/Display/LinesAndRuns/GlyphRun.cs
  CSharpMath/FrontEnd/IGraphicsContext.cs
Labels: Impact/Breaking change, Resolution/Implemented, Type/Housekeeping
