Repository verybadcat/CSharpMath, pull requests merged in 2020-06, with the labels that each got.

#119 Punctuation should stick to inline maths
  CSharpMath.Forms.Example/CSharpMath.Forms.Example.Android/Resources/Resource.designer.cs
  CSharpMath.Rendering.Tests/TestRenderingTextData.cs
  CSharpMath.Rendering.Tests/Text/IntegrationByParts.png
  CSharpMath.Rendering.Tests/Text/PunctuationAffectsLineBreaking.png
  CSharpMath.Rendering.Tests/TextInfiniteWidth/IntegrationByParts.png
  CSharpMath.Rendering.Tests/TextInfiniteWidth/PunctuationAffectsLineBreaking.png
  CSharpMath.Rendering.Text.Tests/TextLaTeXParserTests.cs
  CSharpMath.Rendering/Text/TextAtomListBuilder.cs
  CSharpMath.Rendering/Text/TextLaTeXParser.cs
Labels: Type/Bug

#122 Stick a Status:New label to all non-Chat issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/chat.md
  .github/ISSUE_TEMPLATE/new-feature.md
  .github/ISSUE_TEMPLATE/new-platform.md
  .github/ISSUE_TEMPLATE/outdated-information.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Type/Housekeeping

#127 Upload CI artifacts
  .github/workflows/Build all projects.yml
  .github/workflows/Test all projects.yml
  CSharpMath.CrossPlatform.slnf
  Directory.Build.props
Labels: Type/Housekeeping

#128 Fix punctuation
  CSharpMath.CoreTests/LaTeXParserTest.cs
  CSharpMath.CoreTests/MathListTest.cs
  CSharpMath.Editor.Tests/CaretTests.cs
  CSharpMath.Editor/MathKeyboard.cs
  CSharpMath.Evaluation/Evaluation.cs
  CSharpMath/Atom/Atoms/BinaryOperator.cs
  CSharpMath/Atom/Atoms/Close.cs
  CSharpMath/Atom/Atoms/LargeOperator.cs
  CSharpMath/Atom/Atoms/Number.cs
  CSharpMath/Atom/Atoms/Open.cs
  CSharpMath/Atom/Atoms/Ordinary.cs
  CSharpMath/Atom/Atoms/Punctuation.cs
  CSharpMath/Atom/Atoms/Relation.cs
  CSharpMath/Atom/Atoms/UnaryOperator.cs
  CSharpMath/Atom/LaTeXSettings.cs
Labels: Type/Bug

#129 New shields
  ReadMe.md
Labels: Type/Housekeeping

#130 Add nightly steps to README
  Directory.Build.props
  ReadMe.md
Labels: Type/Housekeeping

#131 Fix dependency version of CI packages + SourceLink infrastructure
  Directory.Build.props
  ReadMe.md
Labels: Resolution/Implemented, Type/Housekeeping

#132 Spacing and bounding boxes (part 1)
  .editorconfig
  CSharpMath.CoreTests/LaTeXParserTest.cs
  CSharpMath.Forms.Example/CSharpMath.Forms.Example/TryPage.xaml
  CSharpMath.Forms.Example/CSharpMath.Forms.Example/TryPage.xaml.cs
  CSharpMath.Rendering.Tests/CSharpMath.Rendering.Tests.csproj
  CSharpMath.Rendering.Tests/MathDisplay/Cases.png
  CSharpMath.Rendering.Tests/MathDisplay/IntegralScripts.png
  CSharpMath.Rendering.Tests/MathDisplay/ItalicAlignment.png
  CSharpMath.Rendering.Tests/MathDisplay/ItalicScripts.png
  CSharpMath.Rendering.Tests/MathDisplay/LargerDelimiters.png
  CSharpMath.Rendering.Tests/MathDisplay/Logic.png
  CSharpMath.Rendering.Tests/MathDisplay/Matrix4.png
  CSharpMath.Rendering.Tests/MathDisplay/Matrix5.png
  CSharpMath.Rendering.Tests/MathDisplay/Matrix6.png
  CSharpMath.Rendering.Tests/MathDisplay/Matrix7.png
  CSharpMath.Rendering.Tests/MathDisplay/SummationBigCup.png
  CSharpMath.Rendering.Tests/MathDisplay/SummationWithCup.png
  CSharpMath.Rendering.Tests/MathInline/Cases.png
  CSharpMath.Rendering.Tests/MathInline/EvalIntegral.png
  CSharpMath.Rendering.Tests/MathInline/Integral.png
  CSharpMath.Rendering.Tests/MathInline/IntegralColorBoxCorrect.png
  CSharpMath.Rendering.Tests/MathInline/IntegralColorBoxWrong.png
  CSharpMath.Rendering.Tests/MathInline/IntegralScripts.png
  CSharpMath.Rendering.Tests/MathInline/ItalicAlignment.png
  CSharpMath.Rendering.Tests/MathInline/ItalicScripts.png
  CSharpMath.Rendering.Tests/MathInline/LargerDelimiters.png
  CSharpMath.Rendering.Tests/MathInline/Logic.png
  CSharpMath.Rendering.Tests/MathInline/Matrix4.png
  CSharpMath.Rendering.Tests/MathInline/Matrix5.png
  CSharpMath.Rendering.Tests/MathInline/Matrix6.png
  CSharpMath.Rendering.Tests/MathInline/Matrix7.png
  CSharpMath.Rendering.Tests/MathInline/ShortIntegral.png
  CSharpMath.Rendering.Tests/MathInline/SummationBigCup.png
  CSharpMath.Rendering.Tests/MathInline/SummationWithCup.png
  CSharpMath.Rendering.Tests/TestRendering.cs
  CSharpMath.Rendering.Tests/TestRenderingMathData.cs
  CSharpMath.Rendering.Tests/TestRendering_SkiaSharp.cs
  CSharpMath.Rendering.Tests/TextCenter/InlineMath.png
  CSharpMath.Rendering.Tests/TextCenterInfiniteWidth/InlineMath.png
  CSharpMath.Rendering.Tests/TextLeft/InlineMath.png
  CSharpMath.Rendering.Tests/TextLeftInfiniteWidth/InlineMath.png
  CSharpMath.Rendering.Tests/TextRight/InlineMath.png
  CSharpMath.Rendering.Tests/TextRightInfiniteWidth/InlineMath.png
  CSharpMath.Rendering/BackEnd/GlyphBoundsProvider.cs
  CSharpMath.Rendering/BackEnd/GraphicsContext.cs
  CSharpMath/Atom/LaTeXParser.cs
  CSharpMath/CSharpMath.csproj
  CSharpMath/Display/Displays/GlyphConstructionDisplay.cs
  CSharpMath/Display/Displays/GlyphDisplay.cs
  CSharpMath/Display/InterElementSpaces.cs
  CSharpMath/Display/Typesetter.cs
  CSharpMath/Extensions/Stack.cs
Labels: Type/Bug

#133 CSharpMath.Ios.Tests
  .github/workflows/Build all projects.yml
  .github/workflows/Test all projects.yml
  CSharpMath.Apple/AppleMathView.cs
  CSharpMath.Ios.Example/IosMathViewController.cs
  CSharpMath.Ios.Tests/AppDelegate.cs
  CSharpMath.Ios.Tests/CSharpMath.Ios.Tests.csproj
  CSharpMath.Ios.Tests/Entitlements.plist
  CSharpMath.Ios.Tests/Info.plist
  CSharpMath.Ios.Tests/LaunchScreen.storyboard
  CSharpMath.Ios.Tests/Main.cs
  CSharpMath.Ios.Tests/Tests.cs
  CSharpMath.Rendering.Tests/TestRendering.cs
  CSharpMath.sln
  Directory.Build.props
  ReadMe.md
Labels: Resolution/Implemented, Type/Housekeeping

#134 Added the bra and ket commands for Dirac notation support
  CSharpMath.CoreTests/LaTeXParserTest.cs
  CSharpMath.Rendering.Tests/MathDisplay/BraSum.png
  CSharpMath.Rendering.Tests/MathDisplay/KetSum.png
  CSharpMath.Rendering.Tests/MathDisplay/LargeBra.png
  CSharpMath.Rendering.Tests/MathDisplay/LargeKet.png
  CSharpMath.Rendering.Tests/MathInline/BraSum.png
  CSharpMath.Rendering.Tests/MathInline/KetSum.png
  CSharpMath.Rendering.Tests/MathInline/LargeBra.png
  CSharpMath.Rendering.Tests/MathInline/LargeKet.png
  CSharpMath.Rendering.Tests/TestRenderingMathData.cs
  CSharpMath/Atom/LaTeXParser.cs
Labels: Type/Enhancement

#139 Enable CSharpMath.Rendering.Tests.TextPainterSettings
  .github/workflows/Test all projects.yml
  CSharpMath.Apple/AppleMathView.cs
  CSharpMath.Ios.Tests/Tests.cs
  CSharpMath.Rendering.Tests/TestRendering.cs
  CSharpMath.Rendering.Tests/TextPainterSettings/Baseline.png
  CSharpMath.Rendering.Tests/TextPainterSettings/GlyphBoxColor.png
  CSharpMath.Rendering.Tests/TextPainterSettings/LocalTypeface.png
  CSharpMath.Rendering.Tests/TextPainterSettings/Magnification.png
  CSharpMath.Rendering.Tests/TextPainterSettings/ScriptLineStyle.png
  CSharpMath.Rendering.Tests/TextPainterSettings/ScriptScriptLineStyle.png
  CSharpMath.Rendering.Tests/TextPainterSettings/Stroke.png
  CSharpMath.Rendering.Tests/TextPainterSettings/TextColor.png
  CSharpMath.Rendering.Tests/TextPainterSettings/TextLineStyle.png
Labels: Type/Housekeeping
